# Generated by Django 5.2.8 on 2025-11-07 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('non_binary', 'Non-binary')], max_length=20)),
                ('playing_position', models.CharField(choices=[('GS', 'Goal Shooter'), ('GA', 'Goal Attack'), ('WA', 'Wing Attack'), ('C', 'Centre'), ('WD', 'Wing Defence'), ('GD', 'Goal Defence'), ('GK', 'Goal Keeper')], max_length=3)),
                ('photo', models.ImageField(blank=True, default='defaults/player-placeholder.png', upload_to='player_photos/')),
                ('institution_name', models.CharField(max_length=255)),
                ('consent_to_play', models.BooleanField(default=False)),
                ('registration_number', models.CharField(editable=False, max_length=4, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
    ]
