# Generated by Django 5.2.8 on 2025-11-07 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('players', '0001_initial'),
        ('tournament_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registered_players', to='tournament_admin.tournament'),
        ),
    ]
